sudo: required
languaje: node_js
node_js:
  - "14"
services:
  - docker
  - mongodb 
before_install:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
install:
  - npm install
script:
  - npm test --forceExit
  - docker build -t backendviajes .
deploy:
  provider: script
  skip_clean_up: true
  script:
    heroku container:login;
    heroku container:push web -a $HEROKU_APP_NAME;
    heroku container:release web -a $HEROKU_APP_NAME;
  branch: main