swagger: "2.0"
info:
  description: "Definición del microservicio de viajes"
  version: "1.0.0"
  title: "Urbanio: Servicio Viajes"
  termsOfService: "http://swagger.io/terms/"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "microservice-travel.herokuapp.com"
basePath: "/api/v1"
tags:

- name: "Viajes"
  description: "gestión del transcurso de viajes"
schemes:
- "https"
- "http"


paths:
  /travels:
    post:
      tags:
      - "Viajes"
      summary: "Añade un nuevo viaje a la lista de viajes en curso"
      description: ""
      operationId: "createViaje"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/travel"
      responses:
        "400":
          description: "Bad Request"
        "201":
          description: "Created"
    get:
      tags:
      - "Viajes"
      summary: "Recibimos todos los viajes"
      description: ""
      operationId: "getAllViajes"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "header"
        name: "x-user"
        required: true
        type: string
      responses:
        "400":
          description: "Bad Request"
        "200":
          description: "successful operation"
  /travels/find:
    get:
      tags:
      - "Viajes"
      summary: "Muestra el listado de viajes con la posibilidad de establecer filtros"
      description: "Se utilizará filtros por id_cliente (el id_cliente ejemplo es 5ffaf5695dc3ce0fa81f16b2) y por estado del viaje"
      operationId: "findTravelbyStatus"
      produces:
      - "application/json"
      parameters:
      - name: "id_cliente"
        in: "query"
        type: "string"
        items:
          type: string
          default: "5ffaf5695dc3ce0fa81f16b2"
      - name: "estado"
        in: "query"
        description: "Status values that need to be considered for filter"
        type: "array"
        items:
          type: "string"
          enum:
          - "FINALIZADO"
          - "EN CURSO"
          default: "EN CURSO"
        collectionFormat: "multi"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/travel"
        "400":
          description: "Invalid status value"

  /travels/{_id}:
    patch:
      tags:
      - "Viajes"
      summary: "Actualiza el estado de un viaje"
      description: ""
      operationId: "patchViaje"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "_id"
        in: "path"
        description: "Identificador de viaje asignado automáticamente por la base de datos. Obtenerlo de alguna llamada get"
        required: true
        type: "string"
        default: "6010bf32641cdf000f3b1a36"
      - name: "body"
        in: "body"
        required: true
        schema:
          $ref: "#/definitions/travel"
      responses:
        "200":
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/travel"
        "400":
          description: "Bad Request"
    delete:
      tags:
      - "Viajes"
      summary: "Eliminación de un viaje por parte del administrador"
      description: ""
      operationId: "deleteViaje"
      parameters:
      - name: "_id"
        in: "path"
        description: "Identificador de viaje asignado automáticamente por la base de datos. Obtenerlo de alguna llamada get"
        required: true
        type: "string"
        default: "6010bf32641cdf000f3b1a36"
      responses:
        "200":
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/travel"
        "400":
          description: "Bad Request"
      
      

definitions:
  travel:
    type: "object"
    properties:
      _id:
        type: "string"
      id_cliente:
        type: "string"
        default: "5ffaf5695dc3ce0fa81f16b2"
      id_vehiculo:
        type: "string"
      estado:
        type: "string"
        enum:
        - "FINALIZADO"
        - "EN CURSO"
      duración:
        type: "string"
        format: "date time"

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"